# Generated by Django 4.0.4 on 2022-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'TEXT'), ('2', 'WARP'), ('3', 'TALK')], max_length=1)),
                ('text', models.TextField(null=True)),
                ('warpto', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
