# Generated by Django 4.0.4 on 2022-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='events',
            field=models.ManyToManyField(null=True, to='mainapp.event'),
        ),
    ]
