# Generated by Django 4.0.4 on 2022-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_location_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='warpor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='warpxy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='warpto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
