# Generated by Django 4.0.4 on 2022-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_event_warpor_event_warpxy_alter_event_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='warpxy',
        ),
        migrations.AddField(
            model_name='event',
            name='warpx',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='warpy',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='warpor',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='warpto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.event'),
        ),
        migrations.AlterField(
            model_name='map',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.location'),
        ),
    ]
