# Generated by Django 4.0.4 on 2022-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_event_warpxy_event_warpx_event_warpy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('startposx', models.PositiveIntegerField(default=1)),
                ('startposy', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('1', 'WALK'), ('2', 'STAY')], max_length=1)),
                ('startposex', models.PositiveIntegerField(default=1)),
                ('startposey', models.PositiveIntegerField(default=1)),
                ('starttop', models.PositiveIntegerField(default=1)),
                ('startleft', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='npcs',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.npc'),
        ),
    ]
