# Generated by Django 4.0.4 on 2022-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_npc_location_npcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='dialog',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
