# Generated by Django 4.0.4 on 2022-05-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_npc_dialog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='startposey',
        ),
        migrations.AlterField(
            model_name='npc',
            name='startposex',
            field=models.CharField(default='down', max_length=5),
        ),
    ]
