# Generated by Django 4.0.4 on 2022-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_npc_startposey_alter_npc_startposex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='warpto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
