# Generated by Django 4.0.4 on 2022-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_event_warpto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='type',
            field=models.CharField(choices=[('1', 'WALK'), ('2', 'STAY'), ('3', 'SPIN')], max_length=1),
        ),
    ]
